### ISSUE TITLE
invalid errors

### ISSUE THREAD

**Issue by TheWylot** [andrei1058/BedWarsProxy#17]

**Comment by TheWylot** [comment]
what is this for?

[15:37:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'bw join random' in com.andrei1058.bedwars.proxy.command.main.MainCommand(bw)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1105) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:334) [patched_1.8.8.jar:git-PaperSpigot-445]
        at com.sekwah.advancedportals.portals.Portal.activate(Portal.java:464) [Advanced-Portals.jar:?]
        at com.sekwah.advancedportals.listeners.Listeners.onMoveEvent(Listeners.java:133) [Advanced-Portals.jar:?]
        at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [patched_1.8.8.jar:git-PaperSpigot-445]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_301]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(Unknown Source) ~[?:1.8.0_301]
        at java.util.TimSort.mergeAt(Unknown Source) ~[?:1.8.0_301]
        at java.util.TimSort.mergeCollapse(Unknown Source) ~[?:1.8.0_301]
        at java.util.TimSort.sort(Unknown Source) ~[?:1.8.0_301]
        at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_301]
        at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_301]
        at com.andrei1058.bedwars.proxy.arenamanager.ArenaManager.joinRandomArena(ArenaManager.java:156) ~[?:?]
        at com.andrei1058.bedwars.proxy.command.main.JoinCMD.execute(JoinCMD.java:35) ~[?:?]
        at com.andrei1058.bedwars.proxy.command.ParentCommand.execute(ParentCommand.java:38) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 26 more

**Comment by JT122406** [comment]
Try using the build on my profile as this build on here has lots of errors that I fixed just waiting for pull request to be accepted
