### ISSUE TITLE
Plugin Wont Load At All...

### ISSUE THREAD

**Issue by real-tonda** [andrei1058/BedWarsProxy#42]
[08:32:54 INFO]: [BedWarsProxy] Enabling BedWarsProxy v${gitVer}1.2.4
[08:32:54 ERROR]: Error occurred while enabling BedWarsProxy v${gitVer}1.2.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.andrei1058.bedwars.proxy.libs.MaterialSupport.getForCurrent(String, String, String)" because the return value of "com.andrei1058.bedwars.proxy.BedWarsProxy.getMaterialAdapter()" is null
	at com.andrei1058.bedwars.proxy.configuration.BedWarsConfig.<init>(BedWarsConfig.java:57) ~[proxy-plugin-1.2.4.jar:?]
	at com.andrei1058.bedwars.proxy.BedWarsProxy.onEnable(BedWarsProxy.java:75) ~[proxy-plugin-1.2.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-317]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-317]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-317]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:32:54 INFO]: [BedWarsProxy] Disabling BedWarsProxy v${gitVer}1.2.4

**Comment by JT122406** [comment]
Use the version in discord it has 1.18.2 support
