### ISSUE TITLE
Flamecord err

### ISSUE THREAD

**Issue by ItzJustSamu** [andrei1058/BedWarsProxy#57]
Error loading plugin BedWarsProxy
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:342) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c4d5b70:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more

**Comment by SunshroomChan** [comment]
Its a Spigot plugin, not a Bungeecord plugin (Flamecord fork)
