### ISSUE TITLE
Error loading plugin BedWarsProxy

### ISSUE THREAD

**Issue by Funasitien** [andrei1058/BedWarsProxy#60]
### Server specs :
- Latest Bungeecord version
-  No config (both bungee and the plugin)

### The error :
[WARNING] Error loading plugin BedWarsProxy
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:341)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 13 more

**Comment by Funasitien** [comment]
Fixed. Missconfig
